DROP TABLE "tnfp-future".dbo.volunteer_period
DROP TABLE "tnfp-future".dbo.volunteer
DROP TABLE "tnfp-future".dbo.metric
DROP TABLE "tnfp-future".dbo.app_user
DROP TABLE "tnfp-future".dbo.program
DROP TABLE "tnfp-future".dbo.metric_category
DROP TABLE "tnfp-future".dbo.metric_name
DROP TABLE "tnfp-future".dbo.measure_type
DROP TABLE "tnfp-future".dbo.job_type
DROP TABLE "tnfp-future".dbo.location
